### ISSUE TITLE
Is there any specific reason allowwindowops is enabled?

### ISSUE THREAD

**Issue by oj002** [toniz4/st#1]
I've modifiying the st source a bit and was wondering if anybody has allowwindowops enabled and what its use case is. Your repo is the only on github were its enabled. Is there any sepcific reason?

https://github.com/toniz4/st/blob/228479f2067eb8889fb3637e5f4967929bbc95a9/config.def.h#L53

**Comment by heyitscassio** [comment]
Is for copying text to the clipboard, using alt c. By default it copies to the primary selection, and is more practical copying to clipboard.
